# Generated by Django 2.0.5 on 2018-07-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRosterDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=30)),
                ('participant_dates', models.CharField(max_length=500)),
                ('per_session_count', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRosterModel',
            fields=[
                ('unique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=15)),
                ('year', models.IntegerField(default=0)),
                ('title', models.CharField(default='Untitled', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='userrosterdetailsmodel',
            name='user_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster_api.UserRosterModel'),
        ),
    ]
