# Generated by Django 2.0.5 on 2018-07-25 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roster_api', '0002_auto_20180723_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrostermodel',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
