# Generated by Django 2.0.5 on 2018-09-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster_api', '0003_auto_20180725_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrosterdetailsmodel',
            name='user_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rosters', to='roster_api.UserRosterModel'),
        ),
    ]
